language: go

go:
  - '1.12.x'

env:
  - GO111MODULE=on

stages:
  - name: test
  - name: release
    if: tag IS present
  - name: deploy
    if: tag IS present

go_import_path: github.com/src-d/lookout-terraform-analyzer

jobs:
  include:
    - name: 'Unit tests'
      stage: test
      script: make test
    - name: 'Push image to Docker Hub'
      stage: release
      script:
        - PKG_OS=linux make packages
        - DOCKER_PUSH_LATEST=true make docker-push
    - name: 'Deploy to staging'
      stage: deploy
      install:
        - make install-helm
      script:
        - HELM_RELEASE=lookout-terraform-analyzer HELM_CHART=lookout-terraform-analyzer K8S_NAMESPACE=lookout HELM_ARGS="--tiller-namespace=lookout --repo https://src-d.github.io/charts/ --set image.tag=$TRAVIS_TAG -f .helm_staging.yml" make deploy
